### ISSUE TITLE
Proposal: Change the way we get data for the contributors list

### ISSUE THREAD

**Issue by JosephusPaye** [NUbots/NUbook#207]
I think we should switch away from the current way we get the data to show the list of contributors to a page (using the git history via the GitHub API) to instead use a list of authors at the top of the file in the frontmatter:

```yaml
---
section: The NUbots Team
chapter: Introduction
title: Introduction to NUbots
description: Learn about what we do, key people, and where to find the lab.
slug: /team/introduction
authors:
  - Ysobel Sims (@ysims)
  - Josephus Paye II (@JosephusPaye)
  - Lachlan Court (@LachlanCourt)
---
```

`authors` will be a list of contributors to the page, with their name followed by GitHub username in parenthesis. Each new person that makes a change to the page simply adds their name and username to the end of the list.

We can then use the author's GithHub username to link to their profile, as well as get their avatar. Given a username, the GitHub profile is at `https://github.com/@username` and the avatar is at `https://github.com/@username.png`.

For the last updated date and link, we can run a git command locally for each page during the build to get the latest commit hash and date. E.g. running the following...

```bash
git log -n1 --pretty='format:%H %cd' --date=format:'%Y-%m-%d' -- src/book/01-team/01-introduction/01-introduction-to-n
ubots.mdx
```

... outputs the commit hash and date:

```
8877c451459e18e6295a7f90d9207f67ef81ce94 2021-07-21
```

The hash can be used to link to the commit: `https://github.com/NUbots/NUbook/commit/<hash_here>`

This approach has many benefits over the current one:

- Resilient to file changes: renaming a file may sometimes loose the edit history, this avoids that
- Resilient to things like auto formatting: you won't get added to the list of contributors if we change the code style and you reformat all files
- Simpler to implement: we don't need to use the GitHub API to fetch the list of contributors at build time

One (albeit minor) downside: if we do this, we'll need a PR that goes through and fills in the details for the current pages.

**Comment by lach-j** [comment]
Seems like a much more reliable and flexible way of doing things and would eliminate all the GitHub issues too.

It doesn't look quite as neat but it may make things easier to organise the authors like this so we don't have to try to split the name and usernames later.
```yaml
---
section: The NUbots Team
chapter: Introduction
title: Introduction to NUbots
description: Learn about what we do, key people, and where to find the lab.
slug: /team/introduction
authors:
  - name: Ysobel Sims
    login: ysims
  - name: Josephus Paye II
    login: JosephusPaye
  - name: Lachlan Court
    login: LachlanCourt
---
```

And for the existing pages it shouldn't be too hard to write a script that grabs the GitHub data and adds it to the mdx file.
